hive-metastore::
	docker build -t ghcr.io/wdpressplus-bigdata/hive-metastore:latest hive-metastore
	docker push ghcr.io/wdpressplus-bigdata/hive-metastore:latest

presto::
	docker build -t ghcr.io/wdpressplus-bigdata/presto:latest presto
	docker push ghcr.io/wdpressplus-bigdata/presto:latest

python::
	docker build -t ghcr.io/wdpressplus-bigdata/python:latest python
	docker push ghcr.io/wdpressplus-bigdata/python:latest

spark::
	docker build -t ghcr.io/wdpressplus-bigdata/spark:latest spark
	docker push ghcr.io/wdpressplus-bigdata/spark:latest
